### ISSUE TITLE
Common Errors and Fixes

### ISSUE THREAD

**Issue by rburghol** [HARPgroup/HSPsquared#56]
Put them here.

**Comment by jdkleiner** [comment]
See error: 

```python 
(hsp2dev_venv) C:\Users\nrf46657\Desktop\GitHub\HSPsquared\tests\testcbp\HSP2results>hsp2 import_uci PL3_5250_0001.uci PL3_5250_0001.h5
Traceback (most recent call last):
  File "C:\Users\nrf46657\virtualenvs\hsp2dev_venv\lib\site-packages\pandas\io\pytables.py", line 1693, in _create_storer
    cls = _TABLE_MAP[tt]
KeyError: None

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\nrf46657\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\nrf46657\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\nrf46657\virtualenvs\hsp2dev_venv\Scripts\hsp2.exe\__main__.py", line 7, in <module>
  File "C:\Users\nrf46657\virtualenvs\hsp2dev_venv\lib\site-packages\HSP2tools\HSP2_CLI.py", line 60, in main
    mando.main()
  File "C:\Users\nrf46657\virtualenvs\hsp2dev_venv\lib\site-packages\mando\core.py", line 208, in __call__
    return self.execute(sys.argv[1:])
  File "C:\Users\nrf46657\virtualenvs\hsp2dev_venv\lib\site-packages\mando\core.py", line 204, in execute
    return command(*a)
  File "C:\Users\nrf46657\virtualenvs\hsp2dev_venv\lib\site-packages\HSP2tools\HSP2_CLI.py", line 40, in import_uci
    readUCI(ucifile, h5file)
  File "C:\Users\nrf46657\virtualenvs\hsp2dev_venv\lib\site-packages\HSP2tools\readUCI.py", line 179, in readUCI
    df = read_hdf(store, path)
  File "C:\Users\nrf46657\virtualenvs\hsp2dev_venv\lib\site-packages\pandas\io\pytables.py", line 425, in read_hdf
    return store.select(
  File "C:\Users\nrf46657\virtualenvs\hsp2dev_venv\lib\site-packages\pandas\io\pytables.py", line 824, in select
    s = self._create_storer(group)
  File "C:\Users\nrf46657\virtualenvs\hsp2dev_venv\lib\site-packages\pandas\io\pytables.py", line 1695, in _create_storer
    raise error("_TABLE_MAP") from err
TypeError: cannot properly create the storer for: [_TABLE_MAP] [group->/PERLND/SNOW/STATES (Group) '',value-><class 'NoneType'>,format->None
```
